### ISSUE TITLE
Modular backup/restore (offline)

### ISSUE THREAD

**Issue by serrq** [davidtakac/bura#11]
To easily restore cities, settings preferences in a new device.

Screenshot has been taken from Libretube app.

![modular-backup](https://github.com/davidtakac/bura/assets/113377431/a690a1d2-6ecb-4768-a1ba-0ec28d8237fe)

**Comment by davidtakac** [comment]
Not planned at this stage because: 

- The app only has around 10 preferences
- Those preferences don't have to be remembered - people generally use only one set of measurement units
- The effort would be disproportionate to the benefit

However, if the Settings grow in complexity, this may become an option. Thank you for the suggestion.
