### ISSUE TITLE
Precipitation percentage isn't properly displayed

### ISSUE THREAD

**Issue by serrq** [davidtakac/bura#16]
OnePlus CPH2399
Android 14
Bura 1.0.2

![1000108600](https://github.com/davidtakac/bura/assets/113377431/c60de1c1-b540-4c19-808c-e6da16e8789d)

**Comment by davidtakac** [comment]
Thanks! Will fix.

**Comment by serrq** [comment]
Do you already suppose where is the issue?
I am not a developer, just I am curious about the process to investigate the issue.

**Comment by davidtakac** [comment]
Thank you for asking :) The horizontal list has a fixed height, which means it cannot expand when its content (the hours) expands. You seem to have increased your phone's font size in the system settings, which causes the content to expand, but since the horizontal list has a fixed height, the content gets "squeezed" to fit and this is what happens. 

The fix will probably be just to make the horizontal list wrap its content. Though I seem to recall making it a fixed height for *some* reason, so it might be a bit more involved than that. We'll see 😄

**Comment by serrq** [comment]
Thanks for the report from the "military" field.

**Comment by serrq** [comment]
Hey dev, when will be available the antisqueeze feature? 😄

**Comment by davidtakac** [comment]
As I thought, proved harder than expected 😄 Still need to fix some things. Shouldn't take too long, though. I'll post here when there's an update.

**Comment by davidtakac** [comment]
1.0.3 is out with this fix. Similar issues are present on the graph screen for larger font sizes, so I'll fix that too.

**Comment by serrq** [comment]
Great job.

![1000108670](https://github.com/davidtakac/bura/assets/113377431/234885f0-ef78-48de-8b97-01905fe34f35)

**Comment by serrq** [comment]
But yesterday the weather forecast in my town was totally wrong ---> I would try another provider.

**Comment by davidtakac** [comment]
Hmm, what's your (general) location and how was it wrong? Could you open a new issue for this?

**Comment by serrq** [comment]
I don't want reveal my geo position.

The provider told rain all day. Clouds and sun, no rain yesterday.

**Comment by davidtakac-cobe** [comment]
Did the icons say rain, or just the probabilities? It's a bit paranoid regarding precipitation probabilities for my location as well.

**Comment by davidtakac** [comment]
Did the icons say rain, or just the probabilities? It's a little paranoid regarding probabilities for my location as well.

**Comment by serrq** [comment]
Probabilities.
