### ISSUE TITLE
Fatal app crash when tap on Longyearbyen

### ISSUE THREAD

**Issue by serrq** [davidtakac/bura#31]
Bura 1.0.5
Android 14
OnePlus CPH2399

I tapped on Utsjoki, then on Longyearbyen, then permanent crashes.
No longer able to launch the app at this moment.

**Comment by davidtakac** [comment]
I recreated the issue and will take a look, thanks. As a workaround, clear your app data and choose another location.

**Comment by serrq** [comment]
Sorry 1.1.0 (also the last one is affected).

**Comment by serrq** [comment]
Hey dev. What was it the problem? String limit max characters?

**Comment by davidtakac** [comment]
Hey, no, Longyearbyen is in the Arctic circle and it's midnight sun currently. Because of this, there are no sunrises or sunsets in the next 6 days. 

When this happens, Open-Meteo just returns epoch second 0 as the sunrise and sunset timestamp for every day as a placeholder. But Bura expects omitted timestamps in that case, which is why it was crashing. 

I fixed it by dropping those placeholder values, as you can see in commit 24dad8d

**Comment by serrq** [comment]
I am not a developer, but a philosopher. Thanks for explanation.

**Comment by davidtakac** [comment]
No problem, thanks for asking :)
