### ISSUE TITLE
Suggestion: remove rounded rectangle borders around graphs

### ISSUE THREAD

**Issue by raj-magesh** [davidtakac/bura#36]
The graphs already have gridlines and the surrounding borders make it look cluttered. Great app, thank you!

**Comment by davidtakac** [comment]
This is how it was before the first release, but the graphs looked asymmetrical because the y-axis labels vary in length. To me, the borders make the screen look more uniform and consistent because all the graphs fit into the same "mould". My eyes know where to look when scrolling more easily.

And I'm glad you're enjoying the app! Thanks for the feedback.
