### ISSUE TITLE
feature req: user option for number of search results

### ISSUE THREAD

**Issue by nutpantz** [davidtakac/bura#6]
I have a very popular town name, the search only gives 10 results.
https://open-meteo.com/en/docs/geocoding-api#name=hope&count=20

My town is down near 15 it so, so in the app i would never see it. Unless..

There was a user option to set more search results provided.

**Comment by davidtakac** [comment]
As a temporary workaround, have you tried searching for the postal code instead? Open-Meteo supports either location name or postal code. I'll try to make the API return more results either way, see #5

**Comment by davidtakac** [comment]
Hey, 1.0.2 is out now with the fix. I made the API return up to 30 results. I think this could be enough for this issue and #5, so I'll close both.  Feel free to reopen if it persists.

Btw, clear app data after installing 1.0.2. I had to change local storage a bit.

**Comment by margerber** [comment]
Hello. Would it be possible to maybe add the coordinates/postcodes to the drop-down list of search results, when looking for a place? There are too many places of the same name around here. :) Thanks.

**Comment by Babber** [comment]
Hi, 
I think this is not quite a satisfactory solution. Even in the above example, there are more than 30 places with the name, 'Hope'. Today I was looking for another place, which is unfortunately also beyond the first 30 hits. So if there must be a limit for the listed search results, it should not be smaller than the occurance of the most popular geographical name on the planet, or rather in the database of Open-Meteo. I see a few ways out:
1. In the first place: is there a good (technical?) reason to put any limit to the hits on this list at all? 
2. If there is, couldn't this limit be set by the user just as the title of this issue suggest? 
3. Alternatively, there could be a 'Load more' button that always shows 10 more hits as long as there are more? 
4. It could also be a solution, if one could search for a place in (a particular region of) a particular country only, e.g. like `Town, Country` or `Town, Region, Country`... To my best understanding, this is not yet possible at the moment.
5. And finally, a welcome feature and a universal solution could be the one suggested in #5, provided of course that the API of the given provider supports this. 
6. Btw, as for the suggestion with the postal code: I have tried this with a few postal codes in Chile, it didn't work. But even where it works, the issue is the same: if you are in luck, the place you look for makes it to the list, but otherwise it may as well get discarded if it's not within the first 30 hits (also tested and confirmed).

Many thanks for your consideration!
